str = ''		
str += '<div id="footer">'
str += '	<div class="inner">'
str += ''
str += '		<ul class="add">'
str += '			<li><a href="privacy.html">개인정보처리방침</a></li>'
str += '			<li><a href="terms.html">이용약관</a><span class="bar"></span></li>'
str += '		</ul>'
str += '		<p>서울시 용산구 장문로 60 (동빙고동) Tel. 02-111-1111 &nbsp;&nbsp; Copyright &copy; 2016 행복나눔재단 All Rights Reserved.</p>'
str += '		<div class="family">'
str += '			<a href="javascript:" class="btn_family" title="관련 사이트 보기">Family Site<span class="blind">열기</span></a>'
str += '			<ul class="lst_family">'
str += '				<li><a href="http://www.skhappiness.org" target="_blank" title="행복나눔재단 사이트 바로가기(새창)">행복나눔재단</a></li>'
str += '				<li><a href="http://ihei.yonsei.ac.kr/ihei/index.do" target="_blank" title="연세대학교 고등교육혁신원 사이트 바로가기(새창)">연세대학교 고등교육혁신원</a></li>'
str += '				<li><a href="https://www.hvc.hanyang.ac.kr/index.html" target="_blank" title="한양대학교 사회혁신센터 사이트 바로가기(새창)">한양대학교 사회혁신센터</a></li>'
str += '				<li><a href="https://sksecenter.kaist.ac.kr" target="_blank" title="KAIST 사회적기업가 MBA 사이트 바로가기(새창)">KAIST 사회적기업가 MBA</a></li>'
str += '				<li><a href="http://www.sknewschool.com/web" target="_blank" title="SK 뉴스쿨 사이트 바로가기(새창)">SK 뉴스쿨</a></li>'
str += '				<li><a href="http://www.besunny.com/Main.main.action" target="_blank" title="SK 대학생 자원봉사단 SUNNY 사이트 바로가기(새창)">SK 대학생 자원봉사단 SUNNY</a></li>'
str += '				<li><a href="https://www.skprobono.com" target="_blank" title="SK 프로보노 사이트 바로가기(새창)">SK 프로보노</a></li>'
str += '				<li><a href="http://sit.skhappiness.org" target="_blank" title="Social Innovators Table 사이트 바로가기(새창)">Social Innovators Table</a></li>'
str += '				<li><a href="https://www.sklookie.com" target="_blank" title="청년 소셜 이노베이터 LOOKIE 사이트 바로가기(새창)">청년 소셜 이노베이터 LOOKIE</a></li>'
str += '				<li><a href="https://www.happyalliance.org" target="_blank" title="행복얼라이언스 사이트 바로가기(새창)">행복얼라이언스</a></li>'
str += '			</ul>'
str += '		</div>'
str += ''
str += '	</div>'
str += '</div>'

document.write( str );				