str = ''
str += '<div id="header">'

if ($('body').hasClass("home")) {
	str += '<div class="h_group">'
} else {
	str += '<div class="h_group sub">'
}

str += ''
str += '		<div>'
str += '			<h1>'
str += '				<a href="index.html" class="logo">'
str += '					<span class="blind">ENSI</span>'
str += '				</a>'
str += '				<span class="txt">Educators’ Network for Social Innovation <br>사회혁신교육자네트워크</span>'
str += '			</h1>'
str += '			<div id="gnb">'
str += '				<a href="javascript:" class="btn_menu">'
str += '					<span><i>전체메뉴 열기</i></span>'
str += '				</a>'
str += '				<div class="box">'
str += '					<button type="button" class="btn_close"><span>전체메뉴 닫기</span></button>'
str += '					<ul>'
str += '						<li><a href="ensi.html">About</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="ensi.html">ENSI 소개</a></li>'
str += '									<li><a href="history.html">주요연혁</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="conference.html">SI Network</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="conference.html">ENSI 컨퍼런스</a></li>'
str += '									<li><a href="forum.html">ENSI 포럼</a></li>'
str += '									<li><a href="seminar.html">ENSI 연구세미나</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="competition.html">SI Research</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="competition.html">연구공모 소개 및 Apply</a></li>'
str += '									<li><a href="papers_list.html">연구논문</a></li>'
str += '									<li><a href="insights.html">ENSI Issue Paper</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="curriculum_list.html">SI Education</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="curriculum_list.html">사회혁신 교육 대학</a></li>'
str += '									<li><a href="material_list.html">교육자료</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '						<li><a href="notice_list.html">Community</a>'
str += '							<div class="sub_menu">'
str += '								<ul>'
str += '									<li><a href="notice_list.html">공지사항</a></li>'
str += '									<li><a href="contact.html">Contact</a></li>'
str += '								</ul>'
str += '							</div>'
str += '						</li>'
str += '					</ul>'
str += '				</div>'
str += '			</div>'
str += '			<div class="util_menu">&nbsp;</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += '</div>'

document.write(str)